name: Daily Snapshot (09:00 Dubai)

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC = 09:00 Dubai
  workflow_dispatch: {}

jobs:
  daily_snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run daily snapshot script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          RUN_MODE: daily
        run: |
          python send_once.py
