name: Scheduled Alerts (every 10 minutes)

on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes (UTC)
  workflow_dispatch: {}      # manual run button in Actions UI

jobs:
  send_alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run alert script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          RUN_MODE: alert
        run: |
          python send_once.py
