name: Weekly Recap (Friday 16:00 Dubai)

on:
  schedule:
    - cron: '0 12 * * FRI'   # 12:00 UTC = 16:00 (4 PM) Dubai
  workflow_dispatch: {}       # manual Run workflow button

jobs:
  weekly_recap:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
      NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}   # optional; safe if missing
      RUN_MODE: weekly

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Weekly Recap
        run: |
          python send_once.py
